runtime: nodejs18
instance_class: F1
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  JWT_SECRET: "mysecretkey"
  NODE_ENV: "production"
